site_name: My Docs
nav:
  - Index : index.md
  - About : about.md
  

 
theme:
  name: 'material'
  language: 'es'
  font:
    text: Roboto
    code: Roboto Mono
  plugins: 
  #  - codeinclude 
   - search  

  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    
    
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      # emoji_index: !!python/name:pymdownx.emoji.gemoji
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid          
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@jborissalleg
#     - icon: simple/linkedin
#       link: https://linkedin.com/borissalleg
copyright: Copyright &copy; 2025 Boris Salleg
    